### PR TITLE
fix aot compilation

### PR DESCRIPTION
**Pull request by andrea11**
update module in order to define a static declaration

### CODE REVIEW

**Comment by andrea11** [comment]
Hello, I tried to build my project with --aot flag unsuccessfully. Apparently, use logic inside the module declaration is not possible because it have to be static. So I propose to remove customs providers from forRoot() method. Eventually, it could be possible to use own custom providers, specifying it on providers array in the module that imports angular2-schema-form-module. Could you please check my pull request? 
Thank you

**Comment by ebrehault** [comment]
@pankyka, did you have any AOIT issues since your change in `forRoot`?

**Comment by pankyka** [comment]
@ebrehault I don't have any aot issues, but I didn't updated any dependencies since my change.

**Comment by ebrehault** [comment]
@andrea11 I have tested AOT build, and it seems it was broken because of the last fix in ArrayWidget, and not the module's forRoot method.

I have fixed it (in master branch), and I do build the test project in AOT. Could please have a try on your side?

**Comment by ebrehault** [comment]
@andrea11 oh wait, are you using Angular 5?
Because I have been trying with 4.

**Comment by ebrehault** [comment]
Fix #185

**Pull request merged**
