### PR TITLE
Re-render View on Schema Config Change

### PR DESCRIPTION
**Pull request by ZheyangSong**
+ Update WidgetChooser to redraw views on schema change
+ Fix issue(https://github.com/makinacorpus/angular2-schema-form/issues/85)

### CODE REVIEW

**Comment by ebrehault** [comment]
@ZheyangSong Nice catch! I was sure it was that kind of small thing you can read thousands of time in the code without realizing it was actually the problem :)
Thanks for the fix. I will make a release.

**Comment by ebrehault** [comment]
1.0.0-beta.6 is released

**Comment by ZheyangSong** [comment]
@ebrehault Glad to be able to contribute. I'm happy to know that you guys respond, merge PR and release a new NPM package in a timely manner. Thanks.

As I use this component, I see sort of heavy form markup generated. I'd like to know if there is plan on improving this. Amongst the markup problems, some small relevant things include the rendered action buttons don't have `type` attribute, the generated form mark up is not wrapped by a `form` element and etc. I understand that this project started as an intermediate solution before the `angular-schema-form` community braces `Angular`. But I still wonder if there is any plan on resolving these problems and making it production-ready. Are the users of this component expected to extend/override the lib to fix such problems?

If you can share the design decisions behind this implementation, I probably can help with resolving some of them at spare time.

**Comment by ebrehault** [comment]
> As I use this component, I see sort of heavy form markup generated. I'd like to know if there is plan on improving this.

That's definitely in our plans.

> the generated form mark up is not wrapped by a form element

I am not sure I get what you mean, to me it looks like it is wrapped in a `form` tag.

> I understand that this project started as an intermediate solution before the angular-schema-form community braces Angular.

Well, not exactly, we started it because ASF was not migrating to Angular, but our intent is not to create an intermediary solution (even if we might consider merging our effort with ASF if they decide to move). 

Our objective is totally to get a production-ready version as soon as possible.

> Are the users of this component expected to extend/override the lib to fix such problems?

Certainly not, it should be fix in the core.

> If you can share the design decisions behind this implementation, I probably can help with resolving some of them at spare time.

We are considering changing the implementation (see #78), and the discussion is totally open.
Any help is greatly appreciated :)

**Comment by ZheyangSong** [comment]
@ebrehault Thanks for the detailed answers. I'm exited to know that there is on-going work to make this component better. And I'd certainly be willing to help.

As of the `form` tag, for my case, the outmost tag is `sf-form`. Please refer to the screenshot below). Not sure if I haven't used the component properly.

screen shot 2017-04-21 at 3 17 27 pm

**Comment by ebrehault** [comment]
Oh right! That's actually a regression I hadn't noticed. That's very bad on the semantic point of view.
I made a fix: https://github.com/makinacorpus/angular2-schema-form/commit/364737b4519f6fd103005ac32a5b2fc04fa382ea

**Pull request merged**
